### ISSUE TITLE
change push to use a dynamic file name and script

### ISSUE THREAD

**Issue by toddgeist** [carafe-fm/carafe-bundler#1]
from https://github.com/carafe-fm/carafe-js/issues/1

**Comment by toddgeist** [comment]
I can do a pr on this.  But first a question.

Why not just call a script and hand it the path to the file so it can just import the bundle?  That gets around the too big file issue

**Comment by jeremiahsmall** [comment]
True, since we are already following on the bundle output, that's a good idea. We didn't do it that way for the general purpose "import" script, because that doesn't work from a web page for example, but in this case we're by definition in the local system, so it would be fine. I'd be happy to create an alternate import script for Carafe.fmp12 which accepts a local file path argument.

Speaking of running the import from a web page, if the page could be expected to provide a public url to the bundle, the same idea could work and would make it more robust. I'll see if I can get bundle rendering to work like that in CodeSandbox, and then we could consider that as a third import option.

**Comment by toddgeist** [comment]
we also may want to consider the new URL protocol coming soon.  fmp18:// . maybe the option is just a script call ie 

`fmp://$/MyFile?script=MyScript`
or
`fmp18://$/MyFile?script=MyScript`

**Comment by jeremiahsmall** [comment]
Do you mean that the entire fmpurl could be a single argument? e.g.

```bash
compile-carafe-bundle [-b <output/path/to/new/bundle.json>] [-f "fmp://$/MyFile?script=MyScript"]
```

**Comment by jeremiahsmall** [comment]
Alternatively, we could add it to the config options:

https://github.com/carafe-fm/carafe-bundler/blob/master/src/bundle-config.js

So in your bundle's package.json, you could declare it something like this:

```json
{
  "private": true,
  "name": "carafe-bundle-template",
  "version": "0.0.0",
  "scripts": {
    "validate": "validate-carafe-bundle -b ",
    "import": "extract-carafe-bundle -b ",
    "watch": "render-carafe-source",
    "watch-port": "render-carafe-source -p ",
    "build": "compile-carafe-bundle",
    "push": "compile-carafe-bundle -f"
  },
  "devDependencies": {
    "@carafe-fm/bundler": "^1.0.0"
  },
  "carafe": {
    "pushFmpUrl": "fmp://$/MyFile?script=MyScript",
    "templateFilename": "src/template.carafe",
    "configFilename": "src/config.json",
    "dataFilename": "src/data.json",
    "metaFilename": "src/meta.json",
    "previewFilename": "src/preview.jpg"
  }
}
```

**Comment by toddgeist** [comment]
having it be one argument is a little bit more flexible at the cost of being a little more fragile.  But I think it might be worth it.  I think in the configs might be a higher priority but either way works

**Comment by jeremiahsmall** [comment]
Speaking of the package.json, I'd love it if the bundler could take advantage of the name and version here, and update it in the meta so the two stay in sync. Right now the two are totally decoupled. Alternatively, I suppose it could be argued that name and version could just be left out of the package.json. Certainly would be simpler.
